// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestRequerst struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRequerst) Reset()         { *m = TestRequerst{} }
func (m *TestRequerst) String() string { return proto.CompactTextString(m) }
func (*TestRequerst) ProtoMessage()    {}
func (*TestRequerst) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *TestRequerst) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRequerst.Unmarshal(m, b)
}
func (m *TestRequerst) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRequerst.Marshal(b, m, deterministic)
}
func (m *TestRequerst) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRequerst.Merge(m, src)
}
func (m *TestRequerst) XXX_Size() int {
	return xxx_messageInfo_TestRequerst.Size(m)
}
func (m *TestRequerst) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRequerst.DiscardUnknown(m)
}

var xxx_messageInfo_TestRequerst proto.InternalMessageInfo

func (m *TestRequerst) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type TestRespone struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestRespone) Reset()         { *m = TestRespone{} }
func (m *TestRespone) String() string { return proto.CompactTextString(m) }
func (*TestRespone) ProtoMessage()    {}
func (*TestRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *TestRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestRespone.Unmarshal(m, b)
}
func (m *TestRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestRespone.Marshal(b, m, deterministic)
}
func (m *TestRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestRespone.Merge(m, src)
}
func (m *TestRespone) XXX_Size() int {
	return xxx_messageInfo_TestRespone.Size(m)
}
func (m *TestRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_TestRespone.DiscardUnknown(m)
}

var xxx_messageInfo_TestRespone proto.InternalMessageInfo

func (m *TestRespone) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*TestRequerst)(nil), "proto.TestRequerst")
	proto.RegisterType((*TestRespone)(nil), "proto.TestRespone")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x72, 0x5c, 0x3c, 0x21, 0xa9,
	0xc5, 0x25, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0x45, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29,
	0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29, 0x4a, 0x8a, 0x5c, 0xdc, 0x10, 0xf9,
	0xe2, 0x82, 0xfc, 0xbc, 0x54, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44, 0xb0, 0x02, 0xce,
	0x20, 0x30, 0xdb, 0xc8, 0x01, 0xa2, 0x24, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x90,
	0x8b, 0xc5, 0x39, 0x31, 0x27, 0x47, 0x48, 0x18, 0x62, 0x91, 0x1e, 0xb2, 0xf1, 0x52, 0x42, 0x28,
	0x82, 0x60, 0x33, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x82, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xed, 0x0c, 0xb3, 0xb9, 0xa0, 0x00, 0x00, 0x00,
}
